version: "3"

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  web1:
    restart: on-failure
    links:
      - my_service_db
    environment:
      - dev=1
      - db_service_name=my_service_db
      - db_name=example_db
      - db_retry_time=3000
    build:
      context: ./web1
      dockerfile: Dockerfile
    ports:
      - "81:5000"

    depends_on:
      - redis
      - my_service_db

  web2:
    restart: on-failure
    links:
      - my_service_db
    environment:
      - dev=1
      - db_service_name=my_service_db
      - db_name=example_db
      - db_retry_time=3000
    build:
      context: ./web2
      dockerfile: Dockerfile
    ports:
      - "82:5000"
    depends_on:
      - redis
      - my_service_db

  my_service_db:
    container_name: my_service_db
    image: mongo
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web1
      - web2

  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    image: telegraf:1.19
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana-storage:/var/lib/grafana:rw
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000

volumes:
  grafana-storage:
  influxdb-storage:
  mongo_data:
